bind_ip = "0.0.0.0"
bind_port = 8000

# Empty = no access restriction.
access_list = ["127.0.0.1"]
shared_secret = ""

# Used as source address when running traceroute
ipv4_source="198.51.100.42"
ipv6_source="2001:db8:42::1"

bird_socket="/var/run/bird/bird.ctl"
bird6_socket="/var/run/bird/bird6.ctl"
